// Copyright 2023 The Parca Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: pkg/arguments/arguments.i

package arguments

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef long long swig_type_18;
typedef long long swig_type_19;
typedef _gostring_ swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
typedef _gostring_ swig_type_23;
typedef _gostring_ swig_type_24;
typedef _gostring_ swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
typedef _gostring_ swig_type_29;
typedef _gostring_ swig_type_30;
typedef _gostring_ swig_type_31;
typedef _gostring_ swig_type_32;
typedef _gostring_ swig_type_33;
typedef long long swig_type_34;
typedef long long swig_type_35;
typedef long long swig_type_36;
typedef long long swig_type_37;
typedef _gostring_ swig_type_38;
typedef _gostring_ swig_type_39;
typedef _gostring_ swig_type_40;
typedef _gostring_ swig_type_41;
typedef _gostring_ swig_type_42;
typedef _gostring_ swig_type_43;
typedef _gostring_ swig_type_44;
typedef _gostring_ swig_type_45;
typedef _gostring_ swig_type_46;
typedef _gostring_ swig_type_47;
extern void _wrap_Swig_free_arguments_f59005541e345fc4(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_arguments_f59005541e345fc4(swig_intgo arg1);
extern swig_type_1 _wrap_DEFAULTINTERVAL_get_arguments_f59005541e345fc4(void);
extern swig_type_2 _wrap_DEFAULTALLOCINTERVAL_get_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_DEFAULTJSTACKDEPTH_get_arguments_f59005541e345fc4(void);
extern swig_type_3 _wrap_EVENTCPU_get_arguments_f59005541e345fc4(void);
extern swig_type_4 _wrap_EVENTALLOC_get_arguments_f59005541e345fc4(void);
extern swig_type_5 _wrap_EVENTLOCK_get_arguments_f59005541e345fc4(void);
extern swig_type_6 _wrap_EVENTWALL_get_arguments_f59005541e345fc4(void);
extern swig_type_7 _wrap_EVENTITIMER_get_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_ACTIONNONE_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_ACTIONSTART_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_ACTIONRESUME_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_ACTIONSTOP_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_ACTIONDUMP_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_ACTIONCHECK_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_ACTIONSTATUS_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_ACTIONMEMINFO_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_ACTIONLIST_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_ACTIONVERSION_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_ACTIONFULLVERSION_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_COUNTERSAMPLES_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_COUNTERTOTAL_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_RINGANY_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_RINGKERNEL_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_RINGUSER_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_STYLESIMPLE_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_STYLEDOTTED_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_STYLESIGNATURES_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_STYLEANNOTATE_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_STYLELIBNAMES_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_STYLENOSEMICOLON_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_CSTACKDEFAULT_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_CSTACKNO_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_CSTACKFP_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_CSTACKDWARF_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_CSTACKLBR_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_OUTPUTNONE_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_OUTPUTTEXT_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_OUTPUTSVG_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_OUTPUTCOLLAPSED_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_OUTPUTFLAMEGRAPH_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_OUTPUTTREE_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_OUTPUTJFR_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_NOSYSTEMINFO_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_NOSYSTEMPROPS_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_NONATIVELIBS_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_NOCPULOAD_arguments_f59005541e345fc4(void);
extern swig_intgo _wrap_JFRSYNCOPTS_arguments_f59005541e345fc4(void);
extern void _wrap_Multiplier_Symbol_set_arguments_f59005541e345fc4(uintptr_t arg1, char arg2);
extern char _wrap_Multiplier_Symbol_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Multiplier_Multiplier_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_8 arg2);
extern swig_type_9 _wrap_Multiplier_Multiplier_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_delete_Multiplier_arguments_f59005541e345fc4(uintptr_t arg1);
extern uintptr_t _wrap_Error_OK_get_arguments_f59005541e345fc4(void);
extern uintptr_t _wrap_new_Error_arguments_f59005541e345fc4(swig_type_10 arg1);
extern swig_type_11 _wrap_Error_Message_arguments_f59005541e345fc4(uintptr_t arg1);
extern _Bool _wrap_Error__bool_operator_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_delete_Error_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Action_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_Action_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Counter_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_Counter_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Ring_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_Ring_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Event_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_12 arg2);
extern swig_type_13 _wrap_Arguments_Event_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Timeout_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_Timeout_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Interval_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_14 arg2);
extern swig_type_15 _wrap_Arguments_Interval_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Alloc_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_16 arg2);
extern swig_type_17 _wrap_Arguments_Alloc_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Lock_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_18 arg2);
extern swig_type_19 _wrap_Arguments_Lock_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Jstackdepth_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_Jstackdepth_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_SafeMode_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_SafeMode_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_File_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_20 arg2);
extern swig_type_21 _wrap_Arguments_File_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Log_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_22 arg2);
extern swig_type_23 _wrap_Arguments_Log_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Loglevel_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_24 arg2);
extern swig_type_25 _wrap_Arguments_Loglevel_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_UnknownArg_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_26 arg2);
extern swig_type_27 _wrap_Arguments_UnknownArg_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Server_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_28 arg2);
extern swig_type_29 _wrap_Arguments_Server_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Filter_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_30 arg2);
extern swig_type_31 _wrap_Arguments_Filter_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Include_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_Include_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Exclude_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_Exclude_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Mcache_set_arguments_f59005541e345fc4(uintptr_t arg1, char arg2);
extern char _wrap_Arguments_Mcache_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Loop_set_arguments_f59005541e345fc4(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_Arguments_Loop_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Threads_set_arguments_f59005541e345fc4(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_Arguments_Threads_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Sched_set_arguments_f59005541e345fc4(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_Arguments_Sched_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Live_set_arguments_f59005541e345fc4(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_Arguments_Live_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Fdtransfer_set_arguments_f59005541e345fc4(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_Arguments_Fdtransfer_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_FdtransferPath_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_32 arg2);
extern swig_type_33 _wrap_Arguments_FdtransferPath_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Style_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_Style_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Cstack_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_Cstack_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Output_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_Output_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_ChunkSize_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_34 arg2);
extern swig_type_35 _wrap_Arguments_ChunkSize_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_ChunkTime_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_36 arg2);
extern swig_type_37 _wrap_Arguments_ChunkTime_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_JfrSync_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_38 arg2);
extern swig_type_39 _wrap_Arguments_JfrSync_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_JfrOptions_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_JfrOptions_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_DumpTraces_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_DumpTraces_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_DumpFlat_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_DumpFlat_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_FileNum_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Arguments_FileNum_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Begin_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_40 arg2);
extern swig_type_41 _wrap_Arguments_Begin_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_End_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_42 arg2);
extern swig_type_43 _wrap_Arguments_End_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Title_set_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_44 arg2);
extern swig_type_45 _wrap_Arguments_Title_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Minwidth_set_arguments_f59005541e345fc4(uintptr_t arg1, double arg2);
extern double _wrap_Arguments_Minwidth_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Reverse_set_arguments_f59005541e345fc4(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_Arguments_Reverse_get_arguments_f59005541e345fc4(uintptr_t arg1);
extern uintptr_t _wrap_new_Arguments__SWIG_0_arguments_f59005541e345fc4(_Bool arg1);
extern uintptr_t _wrap_new_Arguments__SWIG_1_arguments_f59005541e345fc4(void);
extern void _wrap_delete_Arguments_arguments_f59005541e345fc4(uintptr_t arg1);
extern void _wrap_Arguments_Save_arguments_f59005541e345fc4(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Arguments_Parse_arguments_f59005541e345fc4(uintptr_t arg1, swig_type_46 arg2);
extern swig_type_47 _wrap_Arguments_newfile_arguments_f59005541e345fc4(uintptr_t arg1);
extern _Bool _wrap_Arguments_HasOutputFile_arguments_f59005541e345fc4(uintptr_t arg1);
extern _Bool _wrap_Arguments_HasOption_arguments_f59005541e345fc4(uintptr_t arg1, swig_intgo arg2);
#undef intgo
*/
import "C"

import (
	_ "runtime/cgo"
	"sync"
	"unsafe"
)

type _ unsafe.Pointer

var (
	Swig_escape_always_false bool
	Swig_escape_val          interface{}
)

type (
	_swig_fnptr     *byte
	_swig_memberptr *byte
)

type _ sync.Mutex

type swig_gostring struct {
	p uintptr
	n int
}

func swigCopyString(s string) string {
	p := *(*swig_gostring)(unsafe.Pointer(&s))
	r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
	Swig_free(p.p)
	return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_arguments_f59005541e345fc4(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func GetDEFAULTINTERVAL() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_DEFAULTINTERVAL_get_arguments_f59005541e345fc4())
	return swig_r
}

func GetDEFAULTALLOCINTERVAL() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_DEFAULTALLOCINTERVAL_get_arguments_f59005541e345fc4())
	return swig_r
}

func GetDEFAULTJSTACKDEPTH() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_DEFAULTJSTACKDEPTH_get_arguments_f59005541e345fc4())
	return swig_r
}

func GetEVENTCPU() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_EVENTCPU_get_arguments_f59005541e345fc4()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetEVENTALLOC() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_EVENTALLOC_get_arguments_f59005541e345fc4()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetEVENTLOCK() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_EVENTLOCK_get_arguments_f59005541e345fc4()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetEVENTWALL() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_EVENTWALL_get_arguments_f59005541e345fc4()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetEVENTITIMER() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_EVENTITIMER_get_arguments_f59005541e345fc4()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

type Action int

func _swig_getACTIONNONE() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(C._wrap_ACTIONNONE_arguments_f59005541e345fc4())
	return swig_r
}

var ACTIONNONE Action = _swig_getACTIONNONE()

func _swig_getACTIONSTART() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(C._wrap_ACTIONSTART_arguments_f59005541e345fc4())
	return swig_r
}

var ACTIONSTART Action = _swig_getACTIONSTART()

func _swig_getACTIONRESUME() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(C._wrap_ACTIONRESUME_arguments_f59005541e345fc4())
	return swig_r
}

var ACTIONRESUME Action = _swig_getACTIONRESUME()

func _swig_getACTIONSTOP() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(C._wrap_ACTIONSTOP_arguments_f59005541e345fc4())
	return swig_r
}

var ACTIONSTOP Action = _swig_getACTIONSTOP()

func _swig_getACTIONDUMP() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(C._wrap_ACTIONDUMP_arguments_f59005541e345fc4())
	return swig_r
}

var ACTIONDUMP Action = _swig_getACTIONDUMP()

func _swig_getACTIONCHECK() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(C._wrap_ACTIONCHECK_arguments_f59005541e345fc4())
	return swig_r
}

var ACTIONCHECK Action = _swig_getACTIONCHECK()

func _swig_getACTIONSTATUS() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(C._wrap_ACTIONSTATUS_arguments_f59005541e345fc4())
	return swig_r
}

var ACTIONSTATUS Action = _swig_getACTIONSTATUS()

func _swig_getACTIONMEMINFO() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(C._wrap_ACTIONMEMINFO_arguments_f59005541e345fc4())
	return swig_r
}

var ACTIONMEMINFO Action = _swig_getACTIONMEMINFO()

func _swig_getACTIONLIST() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(C._wrap_ACTIONLIST_arguments_f59005541e345fc4())
	return swig_r
}

var ACTIONLIST Action = _swig_getACTIONLIST()

func _swig_getACTIONVERSION() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(C._wrap_ACTIONVERSION_arguments_f59005541e345fc4())
	return swig_r
}

var ACTIONVERSION Action = _swig_getACTIONVERSION()

func _swig_getACTIONFULLVERSION() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(C._wrap_ACTIONFULLVERSION_arguments_f59005541e345fc4())
	return swig_r
}

var ACTIONFULLVERSION Action = _swig_getACTIONFULLVERSION()

type Counter int

func _swig_getCOUNTERSAMPLES() (_swig_ret Counter) {
	var swig_r Counter
	swig_r = (Counter)(C._wrap_COUNTERSAMPLES_arguments_f59005541e345fc4())
	return swig_r
}

var COUNTERSAMPLES Counter = _swig_getCOUNTERSAMPLES()

func _swig_getCOUNTERTOTAL() (_swig_ret Counter) {
	var swig_r Counter
	swig_r = (Counter)(C._wrap_COUNTERTOTAL_arguments_f59005541e345fc4())
	return swig_r
}

var COUNTERTOTAL Counter = _swig_getCOUNTERTOTAL()

type Ring int

func _swig_getRINGANY() (_swig_ret Ring) {
	var swig_r Ring
	swig_r = (Ring)(C._wrap_RINGANY_arguments_f59005541e345fc4())
	return swig_r
}

var RINGANY Ring = _swig_getRINGANY()

func _swig_getRINGKERNEL() (_swig_ret Ring) {
	var swig_r Ring
	swig_r = (Ring)(C._wrap_RINGKERNEL_arguments_f59005541e345fc4())
	return swig_r
}

var RINGKERNEL Ring = _swig_getRINGKERNEL()

func _swig_getRINGUSER() (_swig_ret Ring) {
	var swig_r Ring
	swig_r = (Ring)(C._wrap_RINGUSER_arguments_f59005541e345fc4())
	return swig_r
}

var RINGUSER Ring = _swig_getRINGUSER()

type Style int

func _swig_getSTYLESIMPLE() (_swig_ret Style) {
	var swig_r Style
	swig_r = (Style)(C._wrap_STYLESIMPLE_arguments_f59005541e345fc4())
	return swig_r
}

var STYLESIMPLE Style = _swig_getSTYLESIMPLE()

func _swig_getSTYLEDOTTED() (_swig_ret Style) {
	var swig_r Style
	swig_r = (Style)(C._wrap_STYLEDOTTED_arguments_f59005541e345fc4())
	return swig_r
}

var STYLEDOTTED Style = _swig_getSTYLEDOTTED()

func _swig_getSTYLESIGNATURES() (_swig_ret Style) {
	var swig_r Style
	swig_r = (Style)(C._wrap_STYLESIGNATURES_arguments_f59005541e345fc4())
	return swig_r
}

var STYLESIGNATURES Style = _swig_getSTYLESIGNATURES()

func _swig_getSTYLEANNOTATE() (_swig_ret Style) {
	var swig_r Style
	swig_r = (Style)(C._wrap_STYLEANNOTATE_arguments_f59005541e345fc4())
	return swig_r
}

var STYLEANNOTATE Style = _swig_getSTYLEANNOTATE()

func _swig_getSTYLELIBNAMES() (_swig_ret Style) {
	var swig_r Style
	swig_r = (Style)(C._wrap_STYLELIBNAMES_arguments_f59005541e345fc4())
	return swig_r
}

var STYLELIBNAMES Style = _swig_getSTYLELIBNAMES()

func _swig_getSTYLENOSEMICOLON() (_swig_ret Style) {
	var swig_r Style
	swig_r = (Style)(C._wrap_STYLENOSEMICOLON_arguments_f59005541e345fc4())
	return swig_r
}

var STYLENOSEMICOLON Style = _swig_getSTYLENOSEMICOLON()

type CStack int

func _swig_getCSTACKDEFAULT() (_swig_ret CStack) {
	var swig_r CStack
	swig_r = (CStack)(C._wrap_CSTACKDEFAULT_arguments_f59005541e345fc4())
	return swig_r
}

var CSTACKDEFAULT CStack = _swig_getCSTACKDEFAULT()

func _swig_getCSTACKNO() (_swig_ret CStack) {
	var swig_r CStack
	swig_r = (CStack)(C._wrap_CSTACKNO_arguments_f59005541e345fc4())
	return swig_r
}

var CSTACKNO CStack = _swig_getCSTACKNO()

func _swig_getCSTACKFP() (_swig_ret CStack) {
	var swig_r CStack
	swig_r = (CStack)(C._wrap_CSTACKFP_arguments_f59005541e345fc4())
	return swig_r
}

var CSTACKFP CStack = _swig_getCSTACKFP()

func _swig_getCSTACKDWARF() (_swig_ret CStack) {
	var swig_r CStack
	swig_r = (CStack)(C._wrap_CSTACKDWARF_arguments_f59005541e345fc4())
	return swig_r
}

var CSTACKDWARF CStack = _swig_getCSTACKDWARF()

func _swig_getCSTACKLBR() (_swig_ret CStack) {
	var swig_r CStack
	swig_r = (CStack)(C._wrap_CSTACKLBR_arguments_f59005541e345fc4())
	return swig_r
}

var CSTACKLBR CStack = _swig_getCSTACKLBR()

type Output int

func _swig_getOUTPUTNONE() (_swig_ret Output) {
	var swig_r Output
	swig_r = (Output)(C._wrap_OUTPUTNONE_arguments_f59005541e345fc4())
	return swig_r
}

var OUTPUTNONE Output = _swig_getOUTPUTNONE()

func _swig_getOUTPUTTEXT() (_swig_ret Output) {
	var swig_r Output
	swig_r = (Output)(C._wrap_OUTPUTTEXT_arguments_f59005541e345fc4())
	return swig_r
}

var OUTPUTTEXT Output = _swig_getOUTPUTTEXT()

func _swig_getOUTPUTSVG() (_swig_ret Output) {
	var swig_r Output
	swig_r = (Output)(C._wrap_OUTPUTSVG_arguments_f59005541e345fc4())
	return swig_r
}

var OUTPUTSVG Output = _swig_getOUTPUTSVG()

func _swig_getOUTPUTCOLLAPSED() (_swig_ret Output) {
	var swig_r Output
	swig_r = (Output)(C._wrap_OUTPUTCOLLAPSED_arguments_f59005541e345fc4())
	return swig_r
}

var OUTPUTCOLLAPSED Output = _swig_getOUTPUTCOLLAPSED()

func _swig_getOUTPUTFLAMEGRAPH() (_swig_ret Output) {
	var swig_r Output
	swig_r = (Output)(C._wrap_OUTPUTFLAMEGRAPH_arguments_f59005541e345fc4())
	return swig_r
}

var OUTPUTFLAMEGRAPH Output = _swig_getOUTPUTFLAMEGRAPH()

func _swig_getOUTPUTTREE() (_swig_ret Output) {
	var swig_r Output
	swig_r = (Output)(C._wrap_OUTPUTTREE_arguments_f59005541e345fc4())
	return swig_r
}

var OUTPUTTREE Output = _swig_getOUTPUTTREE()

func _swig_getOUTPUTJFR() (_swig_ret Output) {
	var swig_r Output
	swig_r = (Output)(C._wrap_OUTPUTJFR_arguments_f59005541e345fc4())
	return swig_r
}

var OUTPUTJFR Output = _swig_getOUTPUTJFR()

type JfrOption int

func _swig_getNOSYSTEMINFO() (_swig_ret JfrOption) {
	var swig_r JfrOption
	swig_r = (JfrOption)(C._wrap_NOSYSTEMINFO_arguments_f59005541e345fc4())
	return swig_r
}

var NOSYSTEMINFO JfrOption = _swig_getNOSYSTEMINFO()

func _swig_getNOSYSTEMPROPS() (_swig_ret JfrOption) {
	var swig_r JfrOption
	swig_r = (JfrOption)(C._wrap_NOSYSTEMPROPS_arguments_f59005541e345fc4())
	return swig_r
}

var NOSYSTEMPROPS JfrOption = _swig_getNOSYSTEMPROPS()

func _swig_getNONATIVELIBS() (_swig_ret JfrOption) {
	var swig_r JfrOption
	swig_r = (JfrOption)(C._wrap_NONATIVELIBS_arguments_f59005541e345fc4())
	return swig_r
}

var NONATIVELIBS JfrOption = _swig_getNONATIVELIBS()

func _swig_getNOCPULOAD() (_swig_ret JfrOption) {
	var swig_r JfrOption
	swig_r = (JfrOption)(C._wrap_NOCPULOAD_arguments_f59005541e345fc4())
	return swig_r
}

var NOCPULOAD JfrOption = _swig_getNOCPULOAD()

func _swig_getJFRSYNCOPTS() (_swig_ret JfrOption) {
	var swig_r JfrOption
	swig_r = (JfrOption)(C._wrap_JFRSYNCOPTS_arguments_f59005541e345fc4())
	return swig_r
}

var JFRSYNCOPTS JfrOption = _swig_getJFRSYNCOPTS()

type SwigcptrMultiplier uintptr

func (p SwigcptrMultiplier) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrMultiplier) SwigIsMultiplier() {
}

func (arg1 SwigcptrMultiplier) SetSymbol(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Multiplier_Symbol_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrMultiplier) GetSymbol() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_Multiplier_Symbol_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrMultiplier) SetMultiplier(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Multiplier_Multiplier_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_type_8(_swig_i_1))
}

func (arg1 SwigcptrMultiplier) GetMultiplier() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Multiplier_Multiplier_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteMultiplier(arg1 Multiplier) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Multiplier_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
}

type Multiplier interface {
	Swigcptr() uintptr
	SwigIsMultiplier()
	SetSymbol(arg2 byte)
	GetSymbol() (_swig_ret byte)
	SetMultiplier(arg2 int64)
	GetMultiplier() (_swig_ret int64)
}

type SwigcptrError uintptr

func (p SwigcptrError) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrError) SwigIsError() {
}

func GetErrorOK() (_swig_ret Error) {
	var swig_r Error
	swig_r = (Error)(SwigcptrError(C._wrap_Error_OK_get_arguments_f59005541e345fc4()))
	return swig_r
}

func NewError(arg1 string) (_swig_ret Error) {
	var swig_r Error
	_swig_i_0 := arg1
	swig_r = (Error)(SwigcptrError(C._wrap_new_Error_arguments_f59005541e345fc4(*(*C.swig_type_10)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func (arg1 SwigcptrError) Message() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Error_Message_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrError) X_bool_operator() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Error__bool_operator_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteError(arg1 Error) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Error_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
}

type Error interface {
	Swigcptr() uintptr
	SwigIsError()
	Message() (_swig_ret string)
	X_bool_operator() (_swig_ret bool)
}

type SwigcptrArguments uintptr

func (p SwigcptrArguments) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrArguments) SwigIsArguments() {
}

func (arg1 SwigcptrArguments) SetAction(arg2 Action) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Action_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetAction() (_swig_ret Action) {
	var swig_r Action
	_swig_i_0 := arg1
	swig_r = (Action)(C._wrap_Arguments_Action_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetCounter(arg2 Counter) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Counter_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetCounter() (_swig_ret Counter) {
	var swig_r Counter
	_swig_i_0 := arg1
	swig_r = (Counter)(C._wrap_Arguments_Counter_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetRing(arg2 Ring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Ring_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetRing() (_swig_ret Ring) {
	var swig_r Ring
	_swig_i_0 := arg1
	swig_r = (Ring)(C._wrap_Arguments_Ring_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetEvent(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Event_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_12)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetEvent() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_Event_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetTimeout(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Timeout_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetTimeout() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Arguments_Timeout_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetInterval(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Interval_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_type_14(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetInterval() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Arguments_Interval_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetAlloc(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Alloc_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_type_16(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetAlloc() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Arguments_Alloc_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetLock(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Lock_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_type_18(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetLock() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Arguments_Lock_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetJstackdepth(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Jstackdepth_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetJstackdepth() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Arguments_Jstackdepth_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetSafeMode(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_SafeMode_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetSafeMode() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Arguments_SafeMode_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetFile(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_File_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_20)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetFile() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_File_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetLog(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Log_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_22)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetLog() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_Log_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetLoglevel(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Loglevel_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_24)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetLoglevel() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_Loglevel_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetUnknownArg(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_UnknownArg_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_26)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetUnknownArg() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_UnknownArg_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetServer(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Server_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_28)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetServer() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_Server_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetFilter(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Filter_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_30)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetFilter() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_Filter_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetInclude(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Include_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetInclude() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Arguments_Include_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetExclude(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Exclude_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetExclude() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Arguments_Exclude_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetMcache(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Mcache_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetMcache() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_Arguments_Mcache_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetLoop(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Loop_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetLoop() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Arguments_Loop_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetThreads(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Threads_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetThreads() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Arguments_Threads_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetSched(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Sched_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetSched() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Arguments_Sched_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetLive(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Live_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetLive() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Arguments_Live_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetFdtransfer(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Fdtransfer_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetFdtransfer() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Arguments_Fdtransfer_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetFdtransferPath(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_FdtransferPath_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_32)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetFdtransferPath() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_FdtransferPath_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetStyle(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Style_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetStyle() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Arguments_Style_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetCstack(arg2 CStack) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Cstack_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetCstack() (_swig_ret CStack) {
	var swig_r CStack
	_swig_i_0 := arg1
	swig_r = (CStack)(C._wrap_Arguments_Cstack_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetOutput(arg2 Output) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Output_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetOutput() (_swig_ret Output) {
	var swig_r Output
	_swig_i_0 := arg1
	swig_r = (Output)(C._wrap_Arguments_Output_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetChunkSize(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_ChunkSize_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_type_34(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetChunkSize() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Arguments_ChunkSize_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetChunkTime(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_ChunkTime_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_type_36(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetChunkTime() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Arguments_ChunkTime_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetJfrSync(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_JfrSync_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_38)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetJfrSync() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_JfrSync_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetJfrOptions(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_JfrOptions_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetJfrOptions() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Arguments_JfrOptions_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetDumpTraces(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_DumpTraces_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetDumpTraces() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Arguments_DumpTraces_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetDumpFlat(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_DumpFlat_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetDumpFlat() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Arguments_DumpFlat_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetFileNum(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_FileNum_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetFileNum() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_Arguments_FileNum_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetBegin(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Begin_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_40)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetBegin() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_Begin_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetEnd(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_End_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_42)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetEnd() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_End_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetTitle(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Title_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_44)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrArguments) GetTitle() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_Title_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) SetMinwidth(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Minwidth_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetMinwidth() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Arguments_Minwidth_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) SetReverse(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Arguments_Reverse_set_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrArguments) GetReverse() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Arguments_Reverse_get_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewArguments__SWIG_0(arg1 bool) (_swig_ret Arguments) {
	var swig_r Arguments
	_swig_i_0 := arg1
	swig_r = (Arguments)(SwigcptrArguments(C._wrap_new_Arguments__SWIG_0_arguments_f59005541e345fc4(C._Bool(_swig_i_0))))
	return swig_r
}

func NewArguments__SWIG_1() (_swig_ret Arguments) {
	var swig_r Arguments
	swig_r = (Arguments)(SwigcptrArguments(C._wrap_new_Arguments__SWIG_1_arguments_f59005541e345fc4()))
	return swig_r
}

func NewArguments(a ...interface{}) Arguments {
	argc := len(a)
	if argc == 0 {
		return NewArguments__SWIG_1()
	}
	if argc == 1 {
		return NewArguments__SWIG_0(a[0].(bool))
	}
	panic("No match for overloaded function call")
}

func DeleteArguments(arg1 Arguments) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Arguments_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrArguments) Save(arg2 Arguments) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Arguments_Save_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrArguments) Parse(arg2 string) (_swig_ret Error) {
	var swig_r Error
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Error)(SwigcptrError(C._wrap_Arguments_Parse_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), *(*C.swig_type_46)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrArguments) Newfile() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Arguments_newfile_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrArguments) HasOutputFile() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Arguments_HasOutputFile_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrArguments) HasOption(arg2 JfrOption) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_Arguments_HasOption_arguments_f59005541e345fc4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

type Arguments interface {
	Swigcptr() uintptr
	SwigIsArguments()
	SetAction(arg2 Action)
	GetAction() (_swig_ret Action)
	SetCounter(arg2 Counter)
	GetCounter() (_swig_ret Counter)
	SetRing(arg2 Ring)
	GetRing() (_swig_ret Ring)
	SetEvent(arg2 string)
	GetEvent() (_swig_ret string)
	SetTimeout(arg2 int)
	GetTimeout() (_swig_ret int)
	SetInterval(arg2 int64)
	GetInterval() (_swig_ret int64)
	SetAlloc(arg2 int64)
	GetAlloc() (_swig_ret int64)
	SetLock(arg2 int64)
	GetLock() (_swig_ret int64)
	SetJstackdepth(arg2 int)
	GetJstackdepth() (_swig_ret int)
	SetSafeMode(arg2 int)
	GetSafeMode() (_swig_ret int)
	SetFile(arg2 string)
	GetFile() (_swig_ret string)
	SetLog(arg2 string)
	GetLog() (_swig_ret string)
	SetLoglevel(arg2 string)
	GetLoglevel() (_swig_ret string)
	SetUnknownArg(arg2 string)
	GetUnknownArg() (_swig_ret string)
	SetServer(arg2 string)
	GetServer() (_swig_ret string)
	SetFilter(arg2 string)
	GetFilter() (_swig_ret string)
	SetInclude(arg2 int)
	GetInclude() (_swig_ret int)
	SetExclude(arg2 int)
	GetExclude() (_swig_ret int)
	SetMcache(arg2 byte)
	GetMcache() (_swig_ret byte)
	SetLoop(arg2 bool)
	GetLoop() (_swig_ret bool)
	SetThreads(arg2 bool)
	GetThreads() (_swig_ret bool)
	SetSched(arg2 bool)
	GetSched() (_swig_ret bool)
	SetLive(arg2 bool)
	GetLive() (_swig_ret bool)
	SetFdtransfer(arg2 bool)
	GetFdtransfer() (_swig_ret bool)
	SetFdtransferPath(arg2 string)
	GetFdtransferPath() (_swig_ret string)
	SetStyle(arg2 int)
	GetStyle() (_swig_ret int)
	SetCstack(arg2 CStack)
	GetCstack() (_swig_ret CStack)
	SetOutput(arg2 Output)
	GetOutput() (_swig_ret Output)
	SetChunkSize(arg2 int64)
	GetChunkSize() (_swig_ret int64)
	SetChunkTime(arg2 int64)
	GetChunkTime() (_swig_ret int64)
	SetJfrSync(arg2 string)
	GetJfrSync() (_swig_ret string)
	SetJfrOptions(arg2 int)
	GetJfrOptions() (_swig_ret int)
	SetDumpTraces(arg2 int)
	GetDumpTraces() (_swig_ret int)
	SetDumpFlat(arg2 int)
	GetDumpFlat() (_swig_ret int)
	SetFileNum(arg2 uint)
	GetFileNum() (_swig_ret uint)
	SetBegin(arg2 string)
	GetBegin() (_swig_ret string)
	SetEnd(arg2 string)
	GetEnd() (_swig_ret string)
	SetTitle(arg2 string)
	GetTitle() (_swig_ret string)
	SetMinwidth(arg2 float64)
	GetMinwidth() (_swig_ret float64)
	SetReverse(arg2 bool)
	GetReverse() (_swig_ret bool)
	Save(arg2 Arguments)
	Parse(arg2 string) (_swig_ret Error)
	Newfile() (_swig_ret string)
	HasOutputFile() (_swig_ret bool)
	HasOption(arg2 JfrOption) (_swig_ret bool)
}
