#!/usr/bin/env bash
set -euo pipefail

# Run the configure hook which sets defaults for any config options
"${SNAP}/snap/hooks/configure"

# Grab the config options
log_level="$(snapctl get log-level)"
node="$(snapctl get node)"
http_address="$(snapctl get http-address)"
store="$(snapctl get remote-store-address)"
insecure="$(snapctl get remote-store-insecure)"

# Start building an array of command line options
opts=(
    "--node=${node}"
    "--log-level=${log_level}"
    "--http-address=${http_address}"
    "--remote-store-address=${store}"
    "--remote-store-insecure=${insecure}"
)

# Run parca-agent with the gathered arguments
exec "${SNAP}/parca-agent" "${opts[@]}"
