#!/usr/bin/env bash

# Copyright 2022-2024 The Parca Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# Run the configure hook which sets defaults for any config options
"${SNAP}/meta/hooks/configure"

# Grab the config options
log_level="$(snapctl get log-level)"
node="$(snapctl get node)"
http_address="$(snapctl get http-address)"
store="$(snapctl get remote-store-address)"
insecure="$(snapctl get remote-store-insecure)"
token="$(snapctl get remote-store-bearer-token)"
metadata_external_labels="$(snapctl get metadata-external-labels)"
config_path="$(snapctl get config-path)"

# Start building an array of command line options
opts=(
    "--node=${node}"
    "--log-level=${log_level}"
    "--http-address=${http_address}"
    "--remote-store-address=${store}"
    "--remote-store-insecure=${insecure}"
    "--metadata-external-labels=${metadata_external_labels}"
    "--config-path=${config_path}"
)

# If the token has been changed from empty, append it to the command line args
if [[ -n "${token}" ]]; then
    opts+=("--remote-store-bearer-token=${token}")
fi

# Run parca-agent with the gathered arguments
exec "${SNAP}/parca-agent" "${opts[@]}" 2>&1  | tee -a "$SNAP_COMMON/parca-agent.log"