version: "2"
services:

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest@sha256:0f0b7feb6f02620df7d493ad7437b6ee95b6d16d8d18799f3607124e501444b1
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Jaeger
  jaeger-all-in-one:
    image: docker.io/jaegertracing/all-in-one:latest@sha256:2c9ff429dc8b8fa1dcd46e4e6d230d72e54f35a2e882a072a1735ee5614771d2
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:latest@sha256:e0756467e8ee341a36d279e872db26b92f05bbfbf6027a609d73d8a4298ac9d4
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      # - "4318:4318"   # OTLP HTTP receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
