# hadolint ignore=DL3029
FROM --platform="${BUILDPLATFORM:-linux/amd64}" docker.io/goreleaser/goreleaser-cross:v1.22.0@sha256:b3bd04783a76dade029e1b8dc12ad1fa586578ed747a7a1fd0690e55d8f6f049 AS builder

# hadolint ignore=DL3008
RUN apt-get update -y --no-install-recommends && \
    apt-get install -yq --no-install-recommends\
        libelf-dev zlib1g-dev \
        libelf-dev:arm64 zlib1g-dev:arm64 \
        lld

ARG TARGETARCH=amd64
ARG TARGETOS=linux
ARG TARGETVARIANT

WORKDIR /__w/parca-agent/parca-agent

COPY go.mod go.sum ./
RUN go mod download

ENV GOBIN=/go/bin
# renovate: datasource=go depName=github.com/go-delve/delve
ARG DELVE_VERSION=v1.22.0
# hadolint ignore=DL3059
RUN go install "github.com/go-delve/delve/cmd/dlv@${DELVE_VERSION}"

COPY . ./
RUN goreleaser build --clean --skip-validate --snapshot --debug --id parca-agent-"${TARGETARCH}"

# NOTICE: See goreleaser.yml for the build paths.
RUN mkdir -p /app && \
    if [ "${TARGETARCH}" = 'amd64' ]; then \
        cp "goreleaser/dist/parca-agent-${TARGETARCH}_${TARGETOS}_${TARGETARCH}_${TARGETVARIANT:-v1}/parca-agent" /app/ ; \
    elif [ "${TARGETARCH}" = 'arm' ]; then \
        cp "goreleaser/dist/parca-agent-${TARGETARCH}_${TARGETOS}_${TARGETARCH}_${TARGETVARIANT##v}/parca-agent" /app/ ; \
    else \
        cp "goreleaser/dist/parca-agent-${TARGETARCH}_${TARGETOS}_${TARGETARCH}/parca-agent" /app/ ; \
    fi

# hadolint ignore=DL3029
FROM --platform="${TARGETPLATFORM:-linux/amd64}" gcr.io/distroless/base-debian11@sha256:acdc4f695bd57daad39cf7d305db57eb53ed806c9e894e5249ad58a9cfae370f

COPY --chown=0:0 --from=builder /go/bin/dlv /bin/dlv
COPY --chown=0:0 --from=builder /app/parca-agent /bin/parca-agent
COPY --chown=0:0 parca-agent.yaml /bin/parca-agent.yaml

EXPOSE 7071

ENTRYPOINT ["/bin/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "--continue", "--"]
