# hadolint ignore=DL3029
FROM --platform="${BUILDPLATFORM:-linux/amd64}" docker.io/goreleaser/goreleaser-cross:v1.19.3@sha256:2cac580e0e92d6090b73d232f8e3a87cc04625448b3cbcc939fa1bc9d416fbeb AS builder

# hadolint ignore=DL3008
RUN apt-get update -y --no-install-recommends && \
    apt-get install -yq --no-install-recommends\
        libelf-dev zlib1g-dev \
        libelf-dev:arm64 zlib1g-dev:arm64 \
        lld

ARG TARGETARCH=amd64
ARG TARGETOS=linux
ARG TARGETVARIANT

WORKDIR /__w/parca-agent/parca-agent

COPY go.mod go.sum ./
RUN go mod download

# renovate: datasource=go depName=github.com/go-delve/delve
ARG DELVE_VERSION=v1.9.1
# hadolint ignore=DL3059
RUN go install "github.com/go-delve/delve/cmd/dlv@${DELVE_VERSION}"

COPY . ./
RUN goreleaser build --rm-dist --skip-validate --snapshot --debug --id parca-agent-"${TARGETARCH}"

# NOTICE: See goreleaser.yml for the build paths.
RUN mkdir -p /app && \
   if [ "${TARGETARCH}" = 'amd64' ]; then \
        cp "goreleaser/dist/parca-agent-${TARGETARCH}_${TARGETOS}_${TARGETARCH}_${TARGETVARIANT:-v1}/parca-agent" /app/ ; \
    elif [ "${TARGETARCH}" = 'arm' ]; then \
        cp "goreleaser/dist/parca-agent-${TARGETARCH}_${TARGETOS}_${TARGETARCH}_${TARGETVARIANT##v}/parca-agent" /app/ ; \
    else \
        cp "goreleaser/dist/parca-agent-${TARGETARCH}_${TARGETOS}_${TARGETARCH}/parca-agent" /app/ ; \
    fi

# hadolint ignore=DL3029
FROM --platform="${TARGETPLATFORM:-linux/amd64}" gcr.io/distroless/base-debian11@sha256:122585ba4c098993df9f8dc7285433e8a19974de32528ee3a4b07308808c84ce

COPY --chown=0:0 --from=builder /go/bin/dlv /bin/dlv
COPY --chown=0:0 --from=builder /app/parca-agent /bin/parca-agent

EXPOSE 7071

ENTRYPOINT ["/bin/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "--continue", "--"]
