ARG GOLANG_CROSS_VERSION
# hadolint ignore=DL3029
FROM --platform="${BUILDPLATFORM:-linux/amd64}" docker.io/goreleaser/goreleaser-cross:${GOLANG_CROSS_VERSION}

# hadolint ignore=DL3008
RUN apt-get update -y --no-install-recommends && \
    apt-get install -yq --no-install-recommends \
        libelf-dev zlib1g-dev libzstd-dev \
        libelf-dev:arm64 zlib1g-dev:arm64 libzstd-dev:arm64 \
        lld \
    && rm -rf /var/lib/apt/lists/*
