FROM golang:1.18.1-bullseye

RUN echo "\
deb http://deb.debian.org/debian bullseye-backports main\n\
" >> /etc/apt/sources.list

RUN apt-get update -y && \
      apt-get install --no-install-recommends -y clang-11 llvm-11 make gcc coreutils elfutils binutils zlib1g-dev libelf-dev ca-certificates netbase && \
      ln -s /usr/bin/clang-11 /usr/bin/clang && \
      ln -s /usr/bin/llc-11 /usr/bin/llc

# Install Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY go.mod go.sum /app/
RUN go mod download -modcacherw

COPY Makefile ./
COPY ./3rdparty ./3rdparty
COPY bpf /parca-agent/bpf
RUN make -C bpf setup
RUN make bpf

RUN go install github.com/go-delve/delve/cmd/dlv@v1.8.2

COPY . /app
RUN make build

RUN cp /app/dist/parca-agent /bin/parca-agent
RUN cp /go/bin/dlv /dlv

RUN mkdir -p /tmp

EXPOSE 7071

ENTRYPOINT ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "--continue", "--"]
