apiVersion: v1
kind: Namespace
metadata:
  name: polarsignals
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: polarsignals-agent
  namespace: polarsignals
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: polarsignals-agent
subjects:
- kind: ServiceAccount
  name: polarsignals-agent
  namespace: polarsignals
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: polarsignals-agent
  namespace: polarsignals
  labels:
    app.kubernetes.io/name: polarsignals-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: polarsignals-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: polarsignals-agent
    spec:
      serviceAccount: polarsignals-agent
      hostPID: true
      containers:
      - name: polarsignals-agent
        image: quay.io/polarsignals/polarsignals-agent:latest
        imagePullPolicy: Always
        args:
        - /bin/polarsignals-agent
        - --node=$(NODE_NAME)
          #- --sampling-ratio=0.5
          #- --pod-label-selector=app=my-web-app
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: root
          mountPath: /host/root
          readOnly: true
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: run
          mountPath: /run
        - name: modules
          mountPath: /lib/modules
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: localtime
          mountPath: /etc/localtime
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: root
        hostPath:
          path: /
      - name: proc
        hostPath:
          path: /proc
      - name: run
        hostPath:
          path: /run
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: modules
        hostPath:
          path: /lib/modules
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      - name: localtime
        hostPath:
          path: /etc/localtime
