apiVersion: v1
kind: ServiceAccount
metadata:
  name: polarsignals-agent
  namespace: conprof
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: polarsignals-agent
subjects:
- kind: ServiceAccount
  name: polarsignals-agent
  namespace: conprof
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: polarsignals-agent
  namespace: conprof
  labels:
    app.kubernetes.io/name: polarsignals-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: polarsignals-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: polarsignals-agent
    spec:
      serviceAccount: polarsignals-agent
      hostPID: true
      containers:
      - name: polarsignals-agent
        image: quay.io/polarsignals/polarsignals-agent:latest
        imagePullPolicy: Always
        args:
        - /bin/polarsignals-agent
        - --node=$(NODE_NAME)
        - --log-level=debug
        - --store-address=grpc.polarsignals.com:443
        - --bearer-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0SWQiOiI4NTc5YzlkZS00YmQzLTQzNzYtYjU3NS00OGExN2QzNGI3OWMiLCJ3cml0ZVByb2ZpbGVzIjp0cnVlLCJqdGkiOiJlM2JhODk4Zi0yOTMwLTQyMjQtYmI4MC1jMWQ0ZmJjNGM0NGYiLCJpc3MiOiJodHRwczovL2FwaS5wb2xhcnNpZ25hbHMuY29tLyJ9.joNwtPp5rizAkMnSjYrekhhMkNVPuD2cDAx9tlsa1HQ
          #- --store-address=conprof.conprof.svc:10901
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: root
          mountPath: /host/root
          readOnly: true
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: run
          mountPath: /run
        - name: modules
          mountPath: /lib/modules
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: localtime
          mountPath: /etc/localtime
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: root
        hostPath:
          path: /
      - name: proc
        hostPath:
          path: /proc
      - name: run
        hostPath:
          path: /run
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: modules
        hostPath:
          path: /lib/modules
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      - name: localtime
        hostPath:
          path: /etc/localtime
