// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package probes

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type probeProbeEvent struct {
	_          structs.HostLayout
	KtimeNs    uint64
	DurationNs uint64
	Pid        uint32
	Tid        uint32
	Comm       [16]int8
	SpecId     uint32
	_          [4]byte
}

type probeScopeState struct {
	_       structs.HostLayout
	EntryNs uint64
	Top     uint32
	Pad     uint32
}

// loadProbe returns the embedded CollectionSpec for probe.
func loadProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load probe: %w", err)
	}

	return spec, err
}

// loadProbeObjects loads probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*probeObjects
//	*probePrograms
//	*probeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProbeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// probeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeSpecs struct {
	probeProgramSpecs
	probeMapSpecs
	probeVariableSpecs
}

// probeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeProgramSpecs struct {
	ProbeEntry *ebpf.ProgramSpec `ebpf:"probe_entry"`
	ProbeExit  *ebpf.ProgramSpec `ebpf:"probe_exit"`
}

// probeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeMapSpecs struct {
	ProbeEvents *ebpf.MapSpec `ebpf:"probe_events"`
	ScopeStacks *ebpf.MapSpec `ebpf:"scope_stacks"`
}

// probeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeVariableSpecs struct {
	ProbeEventBtfForce *ebpf.VariableSpec `ebpf:"_probe_event_btf_force"`
}

// probeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeObjects struct {
	probePrograms
	probeMaps
	probeVariables
}

func (o *probeObjects) Close() error {
	return _ProbeClose(
		&o.probePrograms,
		&o.probeMaps,
	)
}

// probeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeMaps struct {
	ProbeEvents *ebpf.Map `ebpf:"probe_events"`
	ScopeStacks *ebpf.Map `ebpf:"scope_stacks"`
}

func (m *probeMaps) Close() error {
	return _ProbeClose(
		m.ProbeEvents,
		m.ScopeStacks,
	)
}

// probeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeVariables struct {
	ProbeEventBtfForce *ebpf.Variable `ebpf:"_probe_event_btf_force"`
}

// probePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probePrograms struct {
	ProbeEntry *ebpf.Program `ebpf:"probe_entry"`
	ProbeExit  *ebpf.Program `ebpf:"probe_exit"`
}

func (p *probePrograms) Close() error {
	return _ProbeClose(
		p.ProbeEntry,
		p.ProbeExit,
	)
}

func _ProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probe_bpfel.o
var _ProbeBytes []byte
