FROM gcr.io/cloud-marketplace-tools/k8s/deployer_envsubst/onbuild

#COPY /tmp/$CHART_NAME.tar.gz /data/chart/
#COPY /tmp/test/$CHART_NAME.tar.gz /data-test/chart/
#COPY /tmp/apptest/schema.yaml /data-test/
COPY schema.yaml /data/
