scrape_configs:
  - job_name: "default"
    scrape_interval: "3s"
    static_configs:
      - targets: [ '127.0.0.1:9090' ]
  - job_name: "parca-server"
    scrape_interval: "3s"
    static_configs:
      - targets: [ 'host.docker.internal:7070' ]
  - job_name: "parca-agent"
    scrape_interval: "3s"
    static_configs:
      - targets: [ 'host.docker.internal:7071' ]
