name: parca-agent
adopt-info: local-parts
summary: Parca Agent is an always-on sampling profiler that uses eBPF
description: |
  Parca Agent is an always-on sampling profiler that uses eBPF to capture raw
  profiling data with very low overhead. It observes user-space and
  kernel-space stacktraces 100 times per second and builds pprof formatted
  profiles from the extracted data.

  The collected data can be viewed locally via HTTP endpoints and then be
  configured to be sent to a Parca server to be queried and analyzed over time.
license: Apache-2.0
contact: https://parca.dev
issues: https://github.com/parca-dev/parca-agent/issues
source-code: https://github.com/parca-dev/parca-agent
website: https://parca.dev
confinement: classic
grade: stable
base: core24
compression: lzo
platforms:
  amd64:
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]

parts:
  local-parts:
    plugin: dump
    source: ./snap/local
    source-type: local
    build-packages:
      - jq
      - libjq1
    override-build: |
      # Set the version of Parca Agent snap based on goreleaser build. Use the tag if one is
      # present, otherwise use the version field which produces a string like "HEAD-c1986c91"
      tag="$(cat metadata.json | jq -r '.tag')"
      if [[ "$tag" == "v0.0.0" ]]; then
        craftctl set version="$(cat metadata.json | jq -r '.version')"
      else
        craftctl set version="$tag"
      fi

      # Copy the binary and wrapper into place
      cp parca-agent $CRAFT_PART_INSTALL/
      cp parca-agent-wrapper $CRAFT_PART_INSTALL/

      chmod 0755 $CRAFT_PART_INSTALL/parca-agent
      chmod 0755 $CRAFT_PART_INSTALL/parca-agent-wrapper
slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON
apps:
  parca-agent:
    command: parca-agent
  parca-agent-svc:
    command: parca-agent-wrapper
    daemon: simple
    install-mode: disable
    restart-condition: always
