name: vmtest
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  kernel-tests:
    name: Kernel tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
        - name: Check out the code
          uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        - name: Install dependencies
          run: sudo apt -y install qemu-system-x86 curl
        - name: Download previously generated initramfs
          uses: actions/download-artifact@v3
          with:
            name: initramfs
            path: kerneltest/
        - name: Run tests
          run: ./kerneltest/vmtest.sh
